# Generated by Django 5.1.5 on 2025-02-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_shoppingcart_user_id_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcart",
            name="recipe_id",
        ),
    ]
